window.DRINK_ORDER_MENU = {
  id: "mcdonalds",
  storeName: "麥當勞",
  menuLabel: "McDonald's",
  subtitle: "這次訂麥當勞，預設是麥香雞搭配經典配餐。",
  hideTemperature: true,
  hiddenControls: ["size", "temperature", "ice", "toppings"],
  categories: ["經典配餐"],
  sugarOptions: ["可樂", "綠茶", "紅茶"],
  iceOptions: ["經典配餐"],
  defaultChoices: {
    size: "套餐",
    temperature: "冷飲",
    sugar: "可樂",
    ice: "經典配餐",
  },
  labels: {
    itemNoun: "餐點",
    itemUnit: "份",
    menuTitle: "選擇主餐",
    orderTitle: "選擇飲料",
    size: "套餐",
    sugar: "飲料",
    ice: "配餐",
    toppings: "加購",
    selectedEmpty: "尚未選擇餐點",
    emptyCart: "尚未加入任何餐點。",
    noResults: "找不到符合的餐點。",
    noToppings: "此套餐沒有加購選項。",
    searchPlaceholder: "輸入主餐名稱",
    itemNotePlaceholder: "例如：可樂去冰、醬包需求",
  },
  toppingPricing: {
    hint: "目前沒有加購項目。",
  },
  toppings: [],
  drinks: [
    {
      id: "mcchicken-classic-meal",
      category: "經典配餐",
      name: "麥香雞搭配經典配餐",
      english: "McChicken classic meal",
      note: "預設主餐。價格目前先以 0 計，若要計算加價請修改此檔 prices.套餐。",
      prices: { "套餐": 0 },
      recommended: true,
    },
    {
      id: "mcnuggets-6-classic-meal",
      category: "經典配餐",
      name: "六塊麥克雞塊套餐",
      english: "6 pc Chicken McNuggets classic meal",
      note: "主餐升級選項。請在 menus/mcdonalds.js 填入加價金額。",
      prices: { "套餐": 0 },
    },
    {
      id: "double-cheeseburger-classic-meal",
      category: "經典配餐",
      name: "雙層牛肉吉事堡套餐",
      english: "Double cheeseburger classic meal",
      note: "主餐升級選項。請在 menus/mcdonalds.js 填入加價金額。",
      prices: { "套餐": 0 },
    },
    {
      id: "big-mac-classic-meal",
      category: "經典配餐",
      name: "大麥克特餐",
      english: "Big Mac classic meal",
      note: "主餐升級選項。請在 menus/mcdonalds.js 填入加價金額。",
      prices: { "套餐": 0 },
    },
  ],
};
