window.DRINK_ORDER_MENU = (() => {
const CATEGORIES = [
  "全部",
  "台灣原茶",
  "朵朵與莎莎",
  "柚香橙韻",
  "水果調飲",
  "香醇鮮乳",
  "醇奶特調",
  "原茶調飲",
  "不失眠",
  "抱抱冬瓜",
];

const DRINKS = [
  {
    id: "alishan-jinxuan",
    category: "台灣原茶",
    name: "手採阿里山金萱",
    english: "Hand picked Alishan Jinxuan tea",
    note: "蘭花、奶油香、茉莉花",
    prices: { L: 40 },
    hot: true,
    recommended: true,
  },
  {
    id: "mingjian-winter-tea",
    category: "台灣原茶",
    name: "名間鄉冬片仔",
    english: "Winter tea",
    note: "花香、奶油香、堅果",
    prices: { L: 35 },
    hot: true,
    recommended: true,
  },
  {
    id: "ruby-black-tea",
    category: "台灣原茶",
    name: "台茶十八號・紅玉",
    english: "Ruby black tea",
    note: "薄荷、肉桂、荔枝",
    prices: { L: 35 },
    hot: true,
    recommended: true,
  },
  {
    id: "biluochun-green",
    category: "台灣原茶",
    name: "碧螺春・綠",
    english: "Biluochun green tea",
    note: "海苔香、豌豆香",
    prices: { L: 30 },
    hot: true,
    recommended: true,
  },
  {
    id: "jinxuan-oolong",
    category: "台灣原茶",
    name: "金萱烏龍",
    english: "Jinxuan oolong tea",
    note: "焙米香、蜂蜜香",
    prices: { L: 30 },
    hot: true,
    recommended: true,
  },
  {
    id: "jinxuan-black",
    category: "台灣原茶",
    name: "著涎金萱紅",
    english: "Jinxuan black tea",
    note: "蜜糖香、莓果香",
    prices: { L: 30 },
    hot: true,
    recommended: true,
  },
  {
    id: "cheese-jinxuan",
    category: "朵朵與莎莎",
    name: "金萱烏龍朵朵",
    english: "Cheese sauce on Jinxuan oolong tea",
    note: "原茶加朵朵",
    prices: { L: 55 },
    hot: true,
    recommended: true,
  },
  {
    id: "cheese-ruby",
    category: "朵朵與莎莎",
    name: "紅玉朵朵",
    english: "Cheese sauce on ruby black tea",
    note: "原茶加朵朵",
    prices: { L: 60 },
    hot: true,
    recommended: true,
  },
  {
    id: "cocoa-cereal-smoothie",
    category: "朵朵與莎莎",
    name: "可可脆片莎莎",
    english: "Cocoa cereal smoothie",
    note: "純冰沙、甜冰固定",
    prices: { L: 110 },
    fixedSugar: "甜冰固定",
    fixedIce: "甜冰固定",
  },
  {
    id: "cocoa-cereal-cheese-smoothie",
    category: "朵朵與莎莎",
    name: "可可脆片朵朵",
    english: "Cheese sauce on cocoa cereal smoothie",
    note: "奶蓋冰沙、甜冰固定",
    prices: { L: 120 },
    fixedSugar: "甜冰固定",
    fixedIce: "甜冰固定",
    recommended: true,
  },
  {
    id: "grapefruit-jinxuan",
    category: "柚香橙韻",
    name: "柚香金萱",
    english: "Grapefruit juice mixed Jinxuan oolong tea",
    note: "葡萄柚果汁，可免費加梅子一顆",
    prices: { L: 55 },
  },
  {
    id: "grapefruit-pulp-jinxuan",
    category: "柚香橙韻",
    name: "柚粒金萱",
    english: "Grapefruit pulp and juice mixed Jinxuan oolong tea",
    note: "葡萄柚果粒，可免費加梅子一顆",
    prices: { L: 65 },
    recommended: true,
  },
  {
    id: "grapefruit-pulp-yakult",
    category: "柚香橙韻",
    name: "柚粒多多",
    english: "Grapefruit pulp and juice mixed Yakult",
    note: "葡萄柚果粒，可免費加梅子一顆",
    prices: { L: 70 },
    caffeineFree: true,
  },
  {
    id: "orange-winter-tea",
    category: "柚香橙韻",
    name: "鮮橙冬片",
    english: "Orange juice mixed winter tea",
    note: "可免費加梅子一顆",
    prices: { L: 60 },
    recommended: true,
  },
  {
    id: "orange-lemon-fruit-tea",
    category: "柚香橙韻",
    name: "鮮橙香檸水果茶",
    english: "Lemon and orange juice mixed Biluochun green tea",
    note: "可免費加梅子一顆",
    prices: { L: 70 },
    recommended: true,
  },
  {
    id: "orange-yakult",
    category: "柚香橙韻",
    name: "鮮橙多多",
    english: "Orange juice mixed Yakult",
    note: "可免費加梅子一顆",
    prices: { L: 75 },
    caffeineFree: true,
  },
  {
    id: "pineapple-jinxuan-black",
    category: "水果調飲",
    name: "鳳梨金萱紅",
    english: "Jinxuan black tea mixed pineapple juice",
    note: "甜度固定",
    prices: { L: 55 },
    fixedSugar: "甜度固定",
    recommended: true,
  },
  {
    id: "lemon-passion-winter-tea",
    category: "水果調飲",
    name: "檸檬 / 百香 冬片仔",
    english: "Winter tea mixed lemon or passion fruit juice",
    note: "檸檬或百香二選一，請寫在備註",
    prices: { L: 50 },
    hot: true,
  },
  {
    id: "lemon-plum-green",
    category: "水果調飲",
    name: "檸檬梅綠",
    english: "Biluochun green tea mixed lemon juice and plum",
    note: "檸檬、梅子、綠茶",
    prices: { L: 50 },
    hot: true,
    recommended: true,
  },
  {
    id: "lemon-passion-yakult",
    category: "水果調飲",
    name: "檸檬 / 百香 多多",
    english: "Lemon or passion fruit juice mixed Yakult",
    note: "檸檬或百香二選一，請寫在備註",
    prices: { L: 70 },
    caffeineFree: true,
  },
  {
    id: "mulberry-ruby",
    category: "水果調飲",
    name: "桑莓紅玉",
    english: "Mulberry juice mixed ruby black tea with sweet agar jelly",
    note: "含原味寒天",
    prices: { L: 60 },
    recommended: true,
  },
  {
    id: "mulberry-fresh-milk",
    category: "水果調飲",
    name: "桑莓鮮奶",
    english: "Mulberry juice mixed fresh milk with sweet agar jelly",
    note: "含原味寒天",
    prices: { M: 65, L: 85 },
    caffeineFree: true,
    recommended: true,
  },
  {
    id: "passion-pearl-coconut",
    category: "水果調飲",
    name: "百香・珍椰",
    english: "Passion fruit with pearl and coconut jelly",
    note: "含珍珠與椰果",
    prices: { L: 55 },
    caffeineFree: true,
    recommended: true,
  },
  {
    id: "ruby-latte",
    category: "香醇鮮乳",
    name: "玉霞紅茶拿鐵",
    english: "Ruby black tea latte",
    note: "鮮乳茶",
    prices: { M: 45, L: 60 },
    hot: true,
    recommended: true,
  },
  {
    id: "jinxuan-latte",
    category: "香醇鮮乳",
    name: "金萱烏龍拿鐵",
    english: "Jinxuan oolong tea latte",
    note: "鮮乳茶",
    prices: { M: 45, L: 60 },
    hot: true,
    recommended: true,
  },
  {
    id: "honey-black-latte",
    category: "香醇鮮乳",
    name: "蜜香紅茶拿鐵",
    english: "Jinxuan black tea latte",
    note: "金萱紅鮮乳茶",
    prices: { M: 45, L: 60 },
    hot: true,
    recommended: true,
  },
  {
    id: "pearl-ruby-latte",
    category: "香醇鮮乳",
    name: "珍珠紅茶拿鐵",
    english: "Ruby black tea latte with pearl",
    note: "含珍珠",
    prices: { M: 45, L: 60 },
    hot: true,
  },
  {
    id: "pearl-coconut-ruby-latte",
    category: "香醇鮮乳",
    name: "珍椰・紅茶拿鐵",
    english: "Ruby black tea latte with pearl and coconut jelly",
    note: "含珍珠與椰果",
    prices: { M: 50, L: 65 },
    hot: true,
    recommended: true,
  },
  {
    id: "almond-ruby-latte",
    category: "香醇鮮乳",
    name: "杏仁凍紅茶拿鐵",
    english: "Ruby black tea latte with almond jelly",
    note: "含杏仁凍",
    prices: { M: 50, L: 65 },
    hot: true,
  },
  {
    id: "adult-cocoa-latte",
    category: "香醇鮮乳",
    name: "大人的可可拿鐵",
    english: "Brown sugar mixed cocoa latte",
    note: "甜度固定",
    prices: { M: 75, L: 90 },
    fixedSugar: "甜度固定",
    hot: true,
    recommended: true,
  },
  {
    id: "brown-sugar-milk-pearl",
    category: "香醇鮮乳",
    name: "黑糖鮮奶珍珠",
    english: "Brown sugar milk with pearl",
    note: "甜度固定",
    prices: { M: 65, L: 85 },
    fixedSugar: "甜度固定",
    hot: true,
    caffeineFree: true,
  },
  {
    id: "ruby-milk-tea",
    category: "醇奶特調",
    name: "玉霞醇奶茶",
    english: "Ruby black milk tea",
    note: "奶精奶茶",
    prices: { M: 35, L: 50 },
    hot: true,
    recommended: true,
  },
  {
    id: "pearl-milk-tea",
    category: "醇奶特調",
    name: "珍珠醇奶茶",
    english: "Ruby black milk tea with pearl",
    note: "含珍珠",
    prices: { M: 35, L: 50 },
    hot: true,
  },
  {
    id: "almond-milk-tea",
    category: "醇奶特調",
    name: "杏仁凍醇奶茶",
    english: "Ruby black milk tea with almond jelly",
    note: "含杏仁凍",
    prices: { M: 40, L: 55 },
  },
  {
    id: "pearl-coconut-milk-tea",
    category: "醇奶特調",
    name: "珍椰・醇奶茶",
    english: "Ruby black milk tea with pearl and coconut jelly",
    note: "含珍珠與椰果",
    prices: { M: 40, L: 55 },
    hot: true,
    recommended: true,
  },
  {
    id: "almond-winter-tea",
    category: "原茶調飲",
    name: "杏仁凍冬片仔",
    english: "Winter tea with almond jelly",
    note: "含杏仁凍",
    prices: { L: 50 },
    recommended: true,
  },
  {
    id: "yakult-green",
    category: "原茶調飲",
    name: "養樂多綠茶",
    english: "Biluochun green tea mixed Yakult",
    note: "養樂多綠茶",
    prices: { L: 50 },
  },
  {
    id: "plum-green",
    category: "原茶調飲",
    name: "春枝梅綠",
    english: "Biluochun green tea with plum",
    note: "梅子綠茶",
    prices: { L: 45 },
    hot: true,
    recommended: true,
  },
  {
    id: "pearl-coconut-jinxuan",
    category: "原茶調飲",
    name: "珍椰・金萱烏龍",
    english: "Jinxuan oolong tea with pearl and coconut jelly",
    note: "含珍珠與椰果",
    prices: { L: 45 },
    hot: true,
    recommended: true,
  },
  {
    id: "buckwheat-tea",
    category: "不失眠",
    name: "不苦蕎麥茶",
    english: "Buckwheat tea",
    note: "花蓮玉里，台灣原產地，農藥 0 檢出",
    prices: { L: 40 },
    hot: true,
    caffeineFree: true,
    recommended: true,
  },
  {
    id: "buckwheat-wintermelon",
    category: "不失眠",
    name: "蕎麥冬露",
    english: "Buckwheat tea mixed wintermelon drink",
    note: "甜度固定",
    prices: { L: 50 },
    fixedSugar: "甜度固定",
    hot: true,
    caffeineFree: true,
  },
  {
    id: "buckwheat-fresh-milk",
    category: "不失眠",
    name: "不苦蕎麥鮮奶",
    english: "Buckwheat tea mixed fresh milk",
    note: "無咖啡因鮮奶茶",
    prices: { L: 65 },
    hot: true,
    caffeineFree: true,
    recommended: true,
  },
  {
    id: "chrysanthemum-tea",
    category: "不失眠",
    name: "黃金菊花茶",
    english: "Chrysanthemum tea",
    note: "苗栗銅鑼，3-11 月期間限定",
    prices: { L: 50 },
    hot: true,
    caffeineFree: true,
    recommended: true,
  },
  {
    id: "chrysanthemum-wintermelon",
    category: "不失眠",
    name: "菊花冬露",
    english: "Chrysanthemum tea mixed wintermelon drink",
    note: "甜度固定，3-11 月期間限定",
    prices: { L: 60 },
    fixedSugar: "甜度固定",
    hot: true,
    caffeineFree: true,
  },
  {
    id: "wintermelon",
    category: "抱抱冬瓜",
    name: "抱抱冬瓜露",
    english: "Wintermelon drink",
    note: "甜度固定，無添加石灰",
    prices: { L: 35 },
    fixedSugar: "甜度固定",
    hot: true,
    caffeineFree: true,
    recommended: true,
  },
  {
    id: "almond-wintermelon",
    category: "抱抱冬瓜",
    name: "杏仁凍冬露",
    english: "Wintermelon drink with almond jelly",
    note: "甜度固定，含杏仁凍",
    prices: { L: 50 },
    fixedSugar: "甜度固定",
    caffeineFree: true,
    recommended: true,
  },
  {
    id: "wintermelon-winter-tea",
    category: "抱抱冬瓜",
    name: "冬露冬片仔",
    english: "Wintermelon drink mixed winter tea",
    note: "甜度固定",
    prices: { L: 45 },
    fixedSugar: "甜度固定",
    hot: true,
    recommended: true,
  },
  {
    id: "lemon-wintermelon",
    category: "抱抱冬瓜",
    name: "檸檬冬露",
    english: "Wintermelon drink mixed lemon juice",
    note: "甜度固定",
    prices: { L: 50 },
    fixedSugar: "甜度固定",
    hot: true,
    caffeineFree: true,
  },
  {
    id: "wintermelon-fresh-milk",
    category: "抱抱冬瓜",
    name: "冬露鮮奶",
    english: "Wintermelon drink mixed fresh milk",
    note: "甜度固定",
    prices: { L: 65 },
    fixedSugar: "甜度固定",
    hot: true,
    caffeineFree: true,
  },
];

const TOPPINGS = [
  { id: "cheese", name: "朵朵奶蓋", price: 25, discountable: false },
  { id: "pearl", name: "珍珠", price: 10, discountable: true },
  { id: "almond", name: "杏仁凍", price: 15, discountable: true },
  { id: "coconut", name: "椰果", price: 15, discountable: true },
  { id: "pearl-coconut", name: "珍椰", price: 15, discountable: true },
  { id: "agar", name: "原味寒天", price: 15, discountable: true },
];

const SUGAR_OPTIONS = ["全糖", "少糖", "半糖", "微糖", "無糖"];
const ICE_OPTIONS = ["多冰", "正常", "少冰", "微冰", "去冰"];
const TEMPERATURE_OPTIONS = ["冷飲", "熱飲"];

  return {
    id: "unocha",
    storeName: "烏弄",
    menuLabel: "Southern Taiwan menu · since 25.08",
    categories: CATEGORIES,
    drinks: DRINKS,
    toppings: TOPPINGS,
    sugarOptions: SUGAR_OPTIONS,
    iceOptions: ICE_OPTIONS,
    temperatureOptions: TEMPERATURE_OPTIONS,
    defaultChoices: {
      size: "L",
      temperature: "冷飲",
      sugar: "少糖",
      ice: "正常",
    },
    toppingPricing: {
      discountSecondPrice: 5,
      hint: "一般配料第 2 份起每份 +$5，朵朵奶蓋另計。",
    },
  };
})();
